### ISSUE TITLE
If uploading to s3, is it possible to set the file as public?

### ISSUE THREAD

**Issue by nathangross** [ArdentHQ/nova-enhanced-markdown#29]
I'm very new to using s3 storage—but I cannot figure out a way to set the uploaded image permission. I'm hoping to not have the entire bucket set as public. 

```
EnhancedMarkdown::make('Body')
  ->hideFromIndex()
  ->alwaysShow()
  ->disk('s3')
  ->path('posts')
                
```
Would I need to use the `parseFile()` function somehow?

Thanks! I love the file up loads with the markdown field!

**Comment by alfonsobries** [comment]
Hi @nathangross, you should be able to use any disk driver, including the `s3` one (I just tested it, and it works).

You may need to google how to configure the s3 server on AWS to be secure, etc, but on laravel side you just need to ensure that the `s3` driver has set the visibility to `public` (on the config/filesystems.php` file), you can also create another disk driver for that purpose (is what I usually do)

For example:

**Comment by ItsANameToo** [comment]
closing this as the above should work for it and no further interaction has occurred since

**Comment by nathangross** [comment]
Yep, thank your for the detailed response. Sorry for the late reply—that worked great!
